"use strict";
// Any Type Variable
//exports.__esModule = true;
var age = 25;
age = true;
console.log(age);
age = "hello";
console.log(age);
age = { name: "lugi" };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push("5");
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: "arif", age: 25 };
console.log(ninja);
ninja = { name: true, age: "25" };
console.log(ninja);
